services:
  db:
    image: postgres:15
    container_name: pos-db
    environment:
      POSTGRES_DB: pos_system_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lalala
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    image: pos-system
    container_name: pos-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pos_system_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: lalala

volumes:
  postgres_data:
